### ISSUE TITLE
Parameters for expert policy

### ISSUE THREAD

**Issue by wsjeon** [ermongroup/multiagent-gail#4]
Dear authors,

Hi. Thank you for sharing your codes. 

Recently, I've been interested in MAGAIL and tried to reproduce your results.
Firstly, I tried to train expert policy as recommended in `README.md` by `python -m sandbox.mack.run_simple`, but I failed. I thought there is a problem on action dimension, so I made all actions as multi-hot vectors and modified relevant terms. After training with MACK, however, it seems like agents cannot recover the appropriate policies similar to MADDPG. 

So I wonder whether it is possible to share the weight files of expert so that readers can simply generate expert trajectories.

Thanks.

**Comment by Ericonaldo** [comment]
Also have a problem on action dimension when running codes follows README.md, with some private path problems...

**Comment by kvas7andy** [comment]
@wsjeon Hi! May I ask if you eventually came up with weights with good performance (for expert trajectories with MACK)? 

I am currently running the cooperative navigarion  _"simple___spread"_ environment, and all losses rise at some point

**Comment by kvas7andy** [comment]
@wsjeon @Ericonaldo An update for the code: I found new implementation of MAGAIL used for the new paper of ermongroup [here](https://github.com/ermongroup/MA-AIRL). The paper is "Multi-Agent Adversarial Inverse Reinforcement Learning".
Results of execution are similar to new paper, but I cannot reach the results of MAGAIL paper (based on the paper "Multi-Agent Generative Adversarial Imitation Learning").

Anyone reached performance from this paper with MAGAIL?

**Comment by LTGgeek** [comment]
Hi all!
I am a rookie in Deep Reinforcement Learning.
Here is a problem when I were running `python -m sandbox.mack.run_simple`.
Here is the log:

```
logging to: /atlas/u/lantaoyu
Traceback (most recent call last):
  File "/home/teng/anaconda3/envs/tensorflow/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/teng/anaconda3/envs/tensorflow/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/teng/Desktop/MA-AIRL-master/multi-agent-irl/sandbox/mack/run_simple.py", line 63, in <module>
    main()
  File "/home/teng/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/teng/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/teng/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/teng/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/teng/Desktop/MA-AIRL-master/multi-agent-irl/sandbox/mack/run_simple.py", line 58, in main
    train(logdir + '/exps/mack/' + env_id + '/l-{}-b-{}/seed-{}'.format(lr, batch_size, seed),
TypeError: must be str, not NoneType
```

Did you have the same problem?
